require("core.options")
require("core.keymaps")
require("core.plugins")
require("core.autocmds")

require("plugins.mason")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.catppuccin")
require("plugins.terminal")
require("plugins.lualine")
